# Generated by Django 3.0.5 on 2020-04-07 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='firstapp',
            name='about',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='firstapp',
            name='image',
            field=models.ImageField(default=2, upload_to='./media'),
            preserve_default=False,
        ),
    ]
