# Generated by Django 3.0.5 on 2020-04-07 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_auto_20200407_0719'),
    ]

    operations = [
        migrations.AddField(
            model_name='firstapp',
            name='category',
            field=models.CharField(choices=[(1, 'Poetry'), (2, 'Technology'), (3, 'Politics'), (4, 'photography')], default=1, max_length=100),
            preserve_default=False,
        ),
    ]
