# Generated by Django 3.0.5 on 2020-04-10 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firstapp',
            name='category',
            field=models.CharField(choices=[('Poetry', 'Poetry'), ('Technology', 'Technology'), ('Politics', 'Politics'), ('photography', 'photography')], max_length=100),
        ),
    ]
