# Generated by Django 3.0.5 on 2020-04-10 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0005_auto_20200410_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='firstapp',
            name='views',
            field=models.IntegerField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
